Somebody once told me the world is gonna roll me
chatwars/chatwars-api-docs pull request #5
Opened 2018-07-27 06:04 UTC by puppy0cam

She was looking kind of dumb trying to declare their own shit, so the documentation shall be changed to fix some levels of stupidity

2018-07-27 06:09 UTC, sad-unicorn requested changes
The thing is, people are not aware that they are declaring. The question is more likely to be 'Why I am getting ACCESS_REFUSED error' 

And there is a third question 'Why I can't login' with answer 'you are trying to access the wrong API instance'

2018-07-28 06:43 UTC, sad-unicorn commented on index.md
> +Interaction is done via AMQP (by rabbitMQ). Application should publish a message to the appropriate exchange with  an appropriate routing key, and then, listen for and react to incoming messages in i
it's not EU, it's international

2018-07-28 06:46 UTC, sad-unicorn requested changes

2018-07-28 06:46 UTC, sad-unicorn commented on index.md
> +| EU | amqps://api.chatwars.me:5673 |
no

2018-07-28 06:46 UTC, sad-unicorn commented on index.md
> +| EU | amqps://api.chatwars.me:5673 |
wronk

2018-07-28 06:46 UTC, sad-unicorn commented on index.md
> +There are two versions of the game with an API, and there are two versionf of the API. Refer to this table for what API to connect to. Be aware that an app will not automatically have the same access
typo 'versionf'

2018-07-28 06:46 UTC, sad-unicorn commented on index.md
> +A: Because they are pre-declared for you. You only have to consume and publish
the real answer is 'security reasons', current answer is wrong

2018-07-28 06:46 UTC, sad-unicorn commented on index.md
> +* To obtain access to [@chtwrsbot (EU)](http://t.me/chtwrsbot)'s API, You must request a login from [@ChatWarsFeedbackBot](http://t.me/ChatWarsFeedbackBot)
int

2018-07-28 08:00 UTC, sad-unicorn approved these changes
its aight

2018-07-28 08:00 UTC, merged

2018-07-28 22:26 UTC, louietyj commented
Lel 100 x "Update changes.md"...