Titles are for losers. Guess I'm a loser then.
chatwars/chatwars-api-docs pull request #6
Opened 2018-08-03 02:39 UTC by puppy0cam

general improvements, and remove a redundant page that is a duplicate of my superior page for the list of queues.

2018-08-03 02:41 UTC, louietyj requested changes

2018-08-03 02:41 UTC, louietyj commented on index.md
> +*Note: Failiure to actually consume from your queue can result in it being revoked*
Nit typo: "Failure"

2018-08-03 02:45 UTC, louietyj requested changes

2018-08-03 02:45 UTC, louietyj commented on results.md
> +- `NotRegistered` - Your app is not yet registered. You must request access to this feature seperately.
Nit typo: "separately"

2018-08-11 04:05 UTC, puppy0cam commented
This pull request now includes the LevelIsLow result

2018-11-11 18:03 UTC, sad-unicorn approved these changes
plz rebase

2018-11-12 07:07 UTC, sad-unicorn commented
I @puppy0cam, I'm not can into rebases!

2018-11-12 07:07 UTC, merged